version: "3"

services:
  node:
    image: node:16
    user: node
    container_name: rocketnet
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secret

  # Serviço que irá rodar o banco de dados
  db:
    container_name: rocketnet_db
    image: mysql:8.0.21
    # platform: linux/x86_64
    restart: always
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
